In [ ]:
import pandas as pd

# Read a single Parquet file
frames = []
for i in range(6):
    frames.append(pd.read_parquet(f'../data/docVQA/test-0000{i}-of-00006.parquet'))
    data = pd.concat(frames)

In [ ]:
len(set(train_df['segment_id']))

In [ ]:
shuffled_df = df.sample(frac=1).reset_index(drop=True)
train_df = shuffled_df[:1500]
test_df = shuffled_df[1500:3000]
extra_data = shuffled_df[3000:]

train_df.to_parquet('train.parquet')
test_df.to_parquet('test.parquet')
extra_data.to_parquet('extra_data.parquet')

In [ ]:
train_df

In [ ]:
images_list = list(train_df['image_id']) + list(test_df['image_id'])
print(len(set(images_list)))

In [ ]:
train_df

In [ ]:
import os
import shutil

for i in images_list:
    src = f'/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/val2014/COCO_val2014_{i:012d}.jpg'
    dst = f'/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/new/COCO_val2014_{i:012d}.jpg'
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)

In [ ]:
from PIL import Image
import io

# Suppose 'image_bytes' contains your image data as bytes
image = Image.open(io.BytesIO(df.iloc[0]['image']['bytes']))

# Now 'image' is a PIL Image object; you can display or process it
image.show()

In [ ]:
print(image

In [ ]:
path = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/PMCVQA/questions/train_2.csv"

df = pd.read_csv(path)

In [ ]:
df

In [ ]:
import json

with open('/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/v2_mscoco_train2014_annotations.json', 'r') as file:
    data = json.load(file)

In [ ]:
data

In [ ]:
path = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/LingoQA/train.parquet"

In [ ]:
df = pd.read_parquet(path)

In [ ]:
df

In [ ]:
import json
path = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/v2_OpenEnded_mscoco_val2014_questions.json"
with open(path, 'r') as file:
    data = json.load(file)

In [ ]:
a = pd.DataFrame(data['questions'])

In [ ]:
import json
path = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/v2_mscoco_val2014_annotations.json"
with open(path, 'r') as file:
    data = json.load(file)

In [ ]:
b = pd.DataFrame(data["annotations"])

In [ ]:
merged_df = pd.merge(a, b, on='question_id', how='inner')

In [ ]:
merged_df

In [ ]:
merged_df = merged_df.drop(["image_id_y"], axis=1)
cols = list(merged_df.columns)
cols[0] = "image_id"
merged_df.columns = cols

In [ ]:
import pandas as pd

path = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/LingoQA/train.parquet"

df = pd.read_parquet(path)

In [ ]:
df

In [ ]:
merged_df

In [ ]:
from PIL import Image
import io

shuffled_df = merged_df.sample(frac=1).reset_index(drop=True)
train_df = shuffled_df[:4000]
test_df = shuffled_df[4000:6000]
extra_data = shuffled_df[6000:]

def load_and_get_bytes(path):
    image = Image.open(f'/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/val2014/COCO_val2014_{path:012d}.jpg')
    img_byte_arr = io.BytesIO()
    image.save(img_byte_arr, format='PNG')
    img_bytes = img_byte_arr.getvalue()
    return img_bytes

def get_image_df(df):
    path_arr = list(df["image_id"])
    image_bytes_arr = []
    for path in path_arr:
        image_bytes_arr.append(load_and_get_bytes(path))
    df['image'] = image_bytes_arr
    return df

train_df = get_image_df(train_df)
test_df = get_image_df(test_df)



train_df.to_parquet('train.parquet')
test_df.to_parquet('test.parquet')

In [ ]:
import pandas as pd

frames = pd.read_parquet("/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/VQA/train.parquet")

In [ ]:
frames

In [ ]:
from PIL import Image
import io

# Suppose 'image_bytes' contains your image data as bytes
image = Image.open(io.BytesIO(frames.iloc[0, -1][1]))

# Now 'image' is a PIL Image object; you can display or process it
image.show()

In [ ]:
train_df.to_parquet('train.parquet')
test_df.to_parquet('test.parquet')

In [ ]:
from PIL import Image
import io

shuffled_df = df.sample(frac=1).reset_index(drop=True)
train_df = shuffled_df[:1500]
test_df = shuffled_df[1500:3000]
extra_data = shuffled_df[3000:]

train_df.to_parquet('train.parquet')
test_df.to_parquet('test.parquet')
extra_data.to_parquet('')

In [1]:
import json
path1 = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/RSVQA/Questions/USGSimages.json"
path2 = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/RSVQA/Questions/USGSquestions.json"
path3 = "/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/RSVQA/Questions/USGSanswers.json"
with open(path1, 'r') as file:
    data1 = json.load(file)
    
with open(path2, 'r') as file:
    data2 = json.load(file)
    
with open(path3, 'r') as file:
    data3 = json.load(file)

In [2]:
data1['images'][0]

{'id': 0,
 'date_added': 1554999793.385965,
 'original_name': 'l_14430346_06_07400_4bd_2013_2048-3072.tif',
 'sensor': 'ULTRACAM_EAGLE_FALCON',
 'upperleft_map_x': -8051919.38848102,
 'upperleft_map_y': 5027837.13596467,
 'res_x': '.1524m',
 'res_y': '.1524m',
 'people_id': 0,
 'type': 'RGB',
 'questions_ids': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
 'active': True}

In [5]:
data2['questions'][0]

{'id': 0,
 'date_added': 1554999793.492056,
 'img_id': 0,
 'people_id': 0,
 'type': 'count',
 'question': 'What is the amount of residential buildings in the image?',
 'answers_ids': [0],
 'active': True}

In [6]:
data3['answers'][0]

{'id': 0,
 'date_added': 1554999793.4920611,
 'question_id': 0,
 'people_id': 0,
 'answer': '3',
 'active': True}

In [11]:
import pandas as pd
images_df = pd.DataFrame(data1['images'])

In [12]:
images_df

,id,date_added,original_name,sensor,upperleft_map_x,upperleft_map_y,res_x,res_y,people_id,type,questions_ids,active
0,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",True
1,1,1.555000e+09,l_14430346_06_07400_4bd_2013_512-3584.tif,ULTRACAM_EAGLE_FALCON,-8.052230e+06,5.027734e+06,.1524m,.1524m,0,RGB,"[100, 101, 102, 103, 104, 105, 106, 107, 108, ...",True
2,2,1.555000e+09,l_14430346_06_07400_4bd_2013_2560-3584.tif,ULTRACAM_EAGLE_FALCON,-8.051816e+06,5.027734e+06,.1524m,.1524m,0,RGB,"[200, 201, 202, 203, 204, 205, 206, 207, 208, ...",True
3,3,1.555000e+09,l_14430346_06_07400_4bd_2013_1024-3072.tif,ULTRACAM_EAGLE_FALCON,-8.052126e+06,5.027837e+06,.1524m,.1524m,0,RGB,"[300, 301, 302, 303, 304, 305, 306, 307, 308, ...",True
4,4,1.555000e+09,l_14430346_06_07400_4bd_2013_1536-3584.tif,ULTRACAM_EAGLE_FALCON,-8.052023e+06,5.027734e+06,.1524m,.1524m,0,RGB,"[400, 401, 402, 403, 404, 405, 406, 407, 408, ...",True
...,...,...,...,...,...,...,...,...,...,...,...,...
10654,10654,1.555330e+09,690227_0-3584.tif,ULTRACAM_EAGLE_FALCON,-8.368667e+06,4.855809e+06,.1524m,.1524m,0,RGB,"[1065816, 1065817, 1065818, 1065819, 1065820, ...",True
10655,10655,1.555330e+09,690227_1024-0.tif,ULTRACAM_EAGLE_FALCON,-8.368463e+06,4.856522e+06,.1524m,.1524m,0,RGB,"[1065916, 1065917, 1065918, 1065919, 1065920, ...",True
10656,10656,1.555330e+09,690227_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.368260e+06,4.855911e+06,.1524m,.1524m,0,RGB,"[1066016, 1066017, 1066018, 1066019, 1066020, ...",True
10657,10657,1.555330e+09,690227_1024-2048.tif,ULTRACAM_EAGLE_FALCON,-8.368463e+06,4.856115e+06,.1524m,.1524m,0,RGB,"[1066116, 1066117, 1066118, 1066119, 1066120, ...",True
10658,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,"[1066216, 1066217, 1066218, 1066219, 1066220, ...",True

In [13]:
shuffled_df = images_df.sample(frac=1).reset_index(drop=True)
train_df = shuffled_df[:1500]
test_df = shuffled_df[1500:3000]
extra_data = shuffled_df[3000:]

In [14]:
train_df

,id,date_added,original_name,sensor,upperleft_map_x,upperleft_map_y,res_x,res_y,people_id,type,questions_ids,active
0,5439,1.555077e+09,990147_2560-2048.tif,ULTRACAM_EAGLE_FALCON,-8.234824e+06,4.949838e+06,.1524m,.1524m,0,RGB,"[544117, 544118, 544119, 544120, 544121, 54412...",True
1,10570,1.555330e+09,690227_2560-2560.tif,ULTRACAM_EAGLE_FALCON,-8.368158e+06,4.856013e+06,.1524m,.1524m,0,RGB,"[1057409, 1057410, 1057411, 1057412, 1057413, ...",True
2,5402,1.555077e+09,990147_3072-1024.tif,ULTRACAM_EAGLE_FALCON,-8.234722e+06,4.950043e+06,.1524m,.1524m,0,RGB,"[540417, 540418, 540419, 540420, 540421, 54042...",True
3,1963,1.555030e+09,l_11970230_06_07400_4bd_2013_4608-2048.tif,ULTRACAM_EAGLE_FALCON,-8.151179e+06,4.982504e+06,.1524m,.1524m,0,RGB,"[196375, 196376, 196377, 196378, 196379, 19638...",True
4,7987,1.555108e+09,987207_512-3584.tif,ULTRACAM_EAGLE_FALCON,-8.236234e+06,4.973695e+06,.1524m,.1524m,0,RGB,"[799006, 799007, 799008, 799009, 799010, 79901...",True
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,6202,1.555086e+09,987210_2048-0.tif,ULTRACAM_EAGLE_FALCON,-8.235925e+06,4.975424e+06,.1524m,.1524m,0,RGB,"[620447, 620448, 620449, 620450, 620451, 62045...",True
1496,10324,1.555327e+09,687222_4096-4096.tif,ULTRACAM_EAGLE_FALCON,-8.368902e+06,4.853745e+06,.1524m,.1524m,0,RGB,"[1032803, 1032804, 1032805, 1032806, 1032807, ...",True
1497,1856,1.555028e+09,052220_512-512.tif,ULTRACAM_EAGLE_FALCON,-8.210110e+06,4.979317e+06,.1524m,.1524m,0,RGB,"[185672, 185673, 185674, 185675, 185676, 18567...",True
1498,7257,1.555101e+09,002235_3584-4096.tif,ULTRACAM_EAGLE_FALCON,-8.229581e+06,4.984685e+06,.1524m,.1524m,0,RGB,"[725979, 725980, 725981, 725982, 725983, 72598...",True
1499,2623,1.555039e+09,l_11940232_06_07400_4bd_2013_1024-1536.tif,ULTRACAM_EAGLE_FALCON,-8.153099e+06,4.983424e+06,.1524m,.1524m,0,RGB,"[262403, 262404, 262405, 262406, 262407, 26240...",True

In [15]:
questions_df = pd.DataFrame(data2['questions'])

In [16]:
questions_df

,id,date_added,img_id,people_id,type,question,answers_ids,active
0,0,1.555000e+09,0,0,count,What is the amount of residential buildings in...,[0],True
1,1,1.555000e+09,0,0,area,What is the area covered by buildings?,[1],True
2,2,1.555000e+09,0,0,count,What is the number of buildings?,[2],True
3,3,1.555000e+09,0,0,comp,Are there more residential buildings than roads?,[3],True
4,4,1.555000e+09,0,0,presence,Is a residential building present?,[4],True
...,...,...,...,...,...,...,...,...
1066311,1066311,1.555330e+09,10658,0,count,How many forests are there?,[1066311],True
1066312,1066312,1.555330e+09,10658,0,presence,Is a industrial area present?,[1066312],True
1066313,1066313,1.555330e+09,10658,0,comp,Are there more farmlands than commercial build...,[1066313],True
1066314,1066314,1.555330e+09,10658,0,comp,Are there less roads than residential buildings?,[1066314],True
1066315,1066315,1.555330e+09,10658,0,presence,Is there a road at the top of a commercial bu...,[1066315],True

In [17]:
answers_df = pd.DataFrame(data3['answers'])

In [21]:
questions_df['answers_ids'] = [i[0] for i in questions_df['answers_ids']]

In [25]:
merged_df = pd.merge(questions_df, answers_df, left_on='answers_ids', right_on = "id", how='inner')

In [26]:
merged_df

,id_x,date_added_x,img_id,people_id_x,type,question,answers_ids,active_x,id_y,date_added_y,question_id,people_id_y,answer,active_y
0,0,1.555000e+09,0,0,count,What is the amount of residential buildings in...,0,True,0,1.555000e+09,0,0,3,True
1,1,1.555000e+09,0,0,area,What is the area covered by buildings?,1,True,1,1.555000e+09,1,0,521m2,True
2,2,1.555000e+09,0,0,count,What is the number of buildings?,2,True,2,1.555000e+09,2,0,4,True
3,3,1.555000e+09,0,0,comp,Are there more residential buildings than roads?,3,True,3,1.555000e+09,3,0,yes,True
4,4,1.555000e+09,0,0,presence,Is a residential building present?,4,True,4,1.555000e+09,4,0,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066311,1066311,1.555330e+09,10658,0,count,How many forests are there?,1066311,True,1066311,1.555330e+09,1066311,0,0,True
1066312,1066312,1.555330e+09,10658,0,presence,Is a industrial area present?,1066312,True,1066312,1.555330e+09,1066312,0,no,True
1066313,1066313,1.555330e+09,10658,0,comp,Are there more farmlands than commercial build...,1066313,True,1066313,1.555330e+09,1066313,0,no,True
1066314,1066314,1.555330e+09,10658,0,comp,Are there less roads than residential buildings?,1066314,True,1066314,1.555330e+09,1066314,0,yes,True
1066315,1066315,1.555330e+09,10658,0,presence,Is there a road at the top of a commercial bu...,1066315,True,1066315,1.555330e+09,1066315,0,no,True

In [27]:
images_df

,id,date_added,original_name,sensor,upperleft_map_x,upperleft_map_y,res_x,res_y,people_id,type,questions_ids,active
0,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",True
1,1,1.555000e+09,l_14430346_06_07400_4bd_2013_512-3584.tif,ULTRACAM_EAGLE_FALCON,-8.052230e+06,5.027734e+06,.1524m,.1524m,0,RGB,"[100, 101, 102, 103, 104, 105, 106, 107, 108, ...",True
2,2,1.555000e+09,l_14430346_06_07400_4bd_2013_2560-3584.tif,ULTRACAM_EAGLE_FALCON,-8.051816e+06,5.027734e+06,.1524m,.1524m,0,RGB,"[200, 201, 202, 203, 204, 205, 206, 207, 208, ...",True
3,3,1.555000e+09,l_14430346_06_07400_4bd_2013_1024-3072.tif,ULTRACAM_EAGLE_FALCON,-8.052126e+06,5.027837e+06,.1524m,.1524m,0,RGB,"[300, 301, 302, 303, 304, 305, 306, 307, 308, ...",True
4,4,1.555000e+09,l_14430346_06_07400_4bd_2013_1536-3584.tif,ULTRACAM_EAGLE_FALCON,-8.052023e+06,5.027734e+06,.1524m,.1524m,0,RGB,"[400, 401, 402, 403, 404, 405, 406, 407, 408, ...",True
...,...,...,...,...,...,...,...,...,...,...,...,...
10654,10654,1.555330e+09,690227_0-3584.tif,ULTRACAM_EAGLE_FALCON,-8.368667e+06,4.855809e+06,.1524m,.1524m,0,RGB,"[1065816, 1065817, 1065818, 1065819, 1065820, ...",True
10655,10655,1.555330e+09,690227_1024-0.tif,ULTRACAM_EAGLE_FALCON,-8.368463e+06,4.856522e+06,.1524m,.1524m,0,RGB,"[1065916, 1065917, 1065918, 1065919, 1065920, ...",True
10656,10656,1.555330e+09,690227_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.368260e+06,4.855911e+06,.1524m,.1524m,0,RGB,"[1066016, 1066017, 1066018, 1066019, 1066020, ...",True
10657,10657,1.555330e+09,690227_1024-2048.tif,ULTRACAM_EAGLE_FALCON,-8.368463e+06,4.856115e+06,.1524m,.1524m,0,RGB,"[1066116, 1066117, 1066118, 1066119, 1066120, ...",True
10658,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,"[1066216, 1066217, 1066218, 1066219, 1066220, ...",True

In [28]:
final_full_df = pd.merge(images_df, merged_df, left_on='id', right_on = "img_id", how='inner')

In [29]:
final_full_df

,id,date_added,original_name,sensor,upperleft_map_x,upperleft_map_y,res_x,res_y,people_id,type_x,...,type_y,question,answers_ids,active_x,id_y,date_added_y,question_id,people_id_y,answer,active_y
0,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,...,count,What is the amount of residential buildings in...,0,True,0,1.555000e+09,0,0,3,True
1,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,...,area,What is the area covered by buildings?,1,True,1,1.555000e+09,1,0,521m2,True
2,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,...,count,What is the number of buildings?,2,True,2,1.555000e+09,2,0,4,True
3,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,...,comp,Are there more residential buildings than roads?,3,True,3,1.555000e+09,3,0,yes,True
4,0,1.555000e+09,l_14430346_06_07400_4bd_2013_2048-3072.tif,ULTRACAM_EAGLE_FALCON,-8.051919e+06,5.027837e+06,.1524m,.1524m,0,RGB,...,presence,Is a residential building present?,4,True,4,1.555000e+09,4,0,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066311,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,...,count,How many forests are there?,1066311,True,1066311,1.555330e+09,1066311,0,0,True
1066312,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,...,presence,Is a industrial area present?,1066312,True,1066312,1.555330e+09,1066312,0,no,True
1066313,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,...,comp,Are there more farmlands than commercial build...,1066313,True,1066313,1.555330e+09,1066313,0,no,True
1066314,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,...,comp,Are there less roads than residential buildings?,1066314,True,1066314,1.555330e+09,1066314,0,yes,True
1066315,10658,1.555330e+09,690227_4608-4096.tif,ULTRACAM_EAGLE_FALCON,-8.367750e+06,4.855708e+06,.1524m,.1524m,0,RGB,...,presence,Is there a road at the top of a commercial bu...,1066315,True,1066315,1.555330e+09,1066315,0,no,True

In [32]:
len(set(list(final_full_df['id'])))

10659

In [44]:
import numpy as np
random_integers = np.random.randint(0, 10658, size=2000)
print(random_integers)

[3072 5858 3964 ... 3871  907 3951]

In [52]:
import random
a = final_full_df[final_full_df['id'].isin(random.sample(list(set(final_full_df['id'])), 2000))]

In [46]:
len(random_integers)

2000

In [53]:
len(set(a['id']))

2000

In [55]:
ids = random.sample(list(set(final_full_df['id'])), 2000)
train_list = random.sample(ids, 1000)
test_list = list(set(ids) - set(train_list))
train_df = final_full_df[final_full_df['id'].isin(train_list)]
test_df = final_full_df[final_full_df['id'].isin(test_list)]

# a = final_full_df[final_full_df['id'].isin(random.sample(list(set(a['id'])), 2000))]

In [59]:
set(test_df['id']).intersection(train_df['id'])

set()

In [60]:
train_df.to_parquet('train.parquet')
test_df.to_parquet('test.parquet')

In [62]:
import os
import shutil

for path in ids:
    src = f'/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/RSVQA/images/{path}.png'
    dst = f'/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/RSVQA/new/{path}.png'
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)

In [85]:
import pandas as pd
df = pd.read_parquet("/Users/shreyansh/Coursework/MMInterpretabilityResearch/Discovering-Domain-Specific-Knowledge-encoded-in-VLMs/data/LingoQA/new/test.parquet")

In [86]:
df

,question_id,segment_id,images,question,answer
1500,b3502c3c395f0b3c2e5403ac3107e723,b6c7ca8c743eb83beeb9f13f2ad5ece7,[images/train/b6c7ca8c743eb83beeb9f13f2ad5ece7...,Where is the white sedan located and in which ...,"The white sedan is directly ahead in my lane, ..."
1501,38b92db2897d7fc88c44cc9cae3134f5,7c8877e22e85299c95990091383010d0,[images/train/7c8877e22e85299c95990091383010d0...,What should you do after the van ahead of you ...,"I should start, accelerate, and follow the van..."
1502,ded1eb856bc2795eb14dbfc0adfb0ffb,f6700c2829ae536d5dd782a4de411055,[images/train/f6700c2829ae536d5dd782a4de411055...,What is the weather condition while you are dr...,"While I am driving, the weather is rainy."
1503,87191a3126e4c87d75ab009dcbe3068d,2540496e93b8d1adc592a710b90c00fb,[images/train/2540496e93b8d1adc592a710b90c00fb...,Is there a cycle lane present?,"Yes, there is a bike lane present."
1504,8beb1e08c0aa0bee8466e57ebff3c130,7e7969282c777a553fce8b206aafb366,[images/train/7e7969282c777a553fce8b206aafb366...,What action are you currently taking as the dr...,I am continuing straight as the road is clear.
...,...,...,...,...,...
2995,4fc55121068135c0497443c3e2f42319,66aea1eaf3ba977e0ec701c69ed075a6,[images/train/66aea1eaf3ba977e0ec701c69ed075a6...,"What are the objects found on the left, apart ...","Apart from vehicles and pedestrians, on the le..."
2996,fc960393ffc47890474c18da497b9c77,1dfbff93bf7a098a6fc42f2efb98bcf1,[images/train/1dfbff93bf7a098a6fc42f2efb98bcf1...,Can you describe the current traffic situation...,There is a stationary black sedan ahead in my ...
2997,2c7f77f8e68ac7d67078cc861460a66e,bad09e5905f6f06c8d3c7d053b3d0449,[images/train/bad09e5905f6f06c8d3c7d053b3d0449...,Can you tell me what lies behind the row of tr...,A SPORTS FIELD
2998,78271f4e82957621d7b1353096422907,36509f38348b551657fa8910f6faa5e9,[images/train/36509f38348b551657fa8910f6faa5e9...,Which side of the road is the dark green SUV p...,The dark green SUV is parked on the right side...
2999,1837a5cf660e5b287b4a9b298ad0202e,25a594245700d8004884762ec05a183a,[images/train/25a594245700d8004884762ec05a183a...,What type of traffic can you observe ahead of ...,There is a stationary black sedan in my lane.

In [68]:
df.iloc[2]['answers']

array([{'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 1},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 2},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 3},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 4},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 5},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 6},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 7},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 8},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 9},
       {'answer': 'yes', 'answer_confidence': 'yes', 'answer_id': 10}],
      dtype=object)